/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import com.sun.glass.ui.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JComboBox;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
 

public class MenuDsn extends javax.swing.JFrame {

    /**
     * Creates new form FormAdmin
     */
    public MenuDsn() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
        
    }
    
//    private void datatable () throws SQLException {
//        DefaultTableModel tbl = new DefaultTableModel();
//        tbl.addColumn("Hari");
//        tbl.addColumn("Jam");
//        tbl.addColumn("Ruang");
//        tbl.addColumn("Mata Kuliah");
//        //table.setModel(tbl);
//        try {
//            Statement statement = (Statement) konek.getConnection().createStatement();
//            ResultSet rs  = statement.executeQuery("select * from");
//            while(rs.next()) 
//            {
//                tbl.addRow(new Object[]{
//                rs.getString("Hari"),
//                rs.getString("Jam"),
//                rs.getString("Ruang"),
//                rs.getString("Mata Kuliah"),
//            });
//            //table.setModel(tbl);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "gagal");
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtextnama = new javax.swing.JTextField();
        jtextnim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUploadNilai = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jtextnilaimhs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxmatkul = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxsemester = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJadwalAjarDosen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtextnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnamaActionPerformed(evt);
            }
        });

        jtextnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnimActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Nim");

        btnUploadNilai.setText("Upload");
        btnUploadNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadNilaiActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel6.setText("Nilai");

        jComboBoxmatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matdis ( semester 4 )", "Kalkulus 1 ( semester 1 )", "B. Inggris ( semester 1 )", "Fisika ( semester 1 )", "Kalkulus 2 ( semester 2 )", "B. Inggris ( semester 2 )", "Fisika ( semester 2 )", "Matrik Vektor ( semester 4 )", "Desain Analis Algoritma ( semester 5 )", "Interaksi Manusia Komputer ( semester 5 )" }));

        jLabel4.setText("Semester");

        jComboBoxsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxsemesterActionPerformed(evt);
            }
        });

        jLabel7.setText("Mata Kuliah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtextnama, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                .addComponent(btnLogout))
                            .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextnim, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUploadNilai)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtextnilaimhs, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtextnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextnilaimhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnUploadNilai)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Upload Nilai", jPanel1);

        tblJadwalAjarDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hari", "Jam", "Ruang", "Mata Kuliah"
            }
        ));
        tblJadwalAjarDosen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblJadwalAjarDosenAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblJadwalAjarDosen);
        if (tblJadwalAjarDosen.getColumnModel().getColumnCount() > 0) {
            tblJadwalAjarDosen.getColumnModel().getColumn(0).setHeaderValue("Hari");
            tblJadwalAjarDosen.getColumnModel().getColumn(1).setHeaderValue("Jam");
            tblJadwalAjarDosen.getColumnModel().getColumn(2).setHeaderValue("Ruang");
            tblJadwalAjarDosen.getColumnModel().getColumn(3).setHeaderValue("Mata Kuliah");
        }

        jLabel1.setText("Jadwal Dosen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(258, 258, 258))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jadwal", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsemesterActionPerformed

    private void jtextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnamaActionPerformed

    private void jtextnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnimActionPerformed

    private void tblJadwalAjarDosenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblJadwalAjarDosenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblJadwalAjarDosenAncestorAdded

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUploadNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadNilaiActionPerformed
//        String nama = jtextnama.getText();
//        String nim  = jtextnim.getText();
//        String smt = (String) jComboBoxsemester.getSelectedItem();
//        String mtkuli = (String) jComboBoxmatkul.getSelectedItem();
//        String nilai= jtextnilaimhs.getText();
//       try{
//        //Statement statement = (Statement) konek.getConnection().createStatement();
////        statement.executeUpdate("insert into mahasiswa VALUES ('" + nama + "','" + nim +"','"+ smt +"','"+ mtkuli +"','"+ nilai +"');");
////        statement.close();
//        JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
//       } catch (Exception t){
//            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
//       }
    }//GEN-LAST:event_btnUploadNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addListener(ActionListener e) {
        btnUploadNilai.addActionListener(e);
        btnLogout.addActionListener(e);
    }

    public void refresh() {
        jtextnim.setText("");
        jtextnama.setText("");
    }
    
    public JButton getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    public JButton getBtnUploadNilai() {
        return btnUploadNilai;
    }

    public void setBtnUploadNilai(JButton btnUploadNilai) {
        this.btnUploadNilai = btnUploadNilai;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JComboBox<String> getjComboBoxmatkul() {
        return jComboBoxmatkul;
    }

    public void setjComboBoxmatkul(JComboBox<String> jComboBoxmatkul) {
        this.jComboBoxmatkul = jComboBoxmatkul;
    }

    public JComboBox<String> getjComboBoxsemester() {
        return jComboBoxsemester;
    }

    public void setjComboBoxsemester(JComboBox<String> jComboBoxsemester) {
        this.jComboBoxsemester = jComboBoxsemester;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getJtextnama() {
        return jtextnama;
    }

    public void setJtextnama(JTextField jtextnama) {
        this.jtextnama = jtextnama;
    }

    public JTextField getJtextnilaimhs() {
        return jtextnilaimhs;
    }

    public void setJtextnilaimhs(JTextField jtextnilaimhs) {
        this.jtextnilaimhs = jtextnilaimhs;
    }

    public JTextField getJtextnim() {
        return jtextnim;
    }

    public void setJtextnim(JTextField jtextnim) {
        this.jtextnim = jtextnim;
    }

    public JTable getTblJadwalAjarDosen() {
        return tblJadwalAjarDosen;
    }

    public void setTblJadwalAjarDosen(JTable tblJadwalAjarDosen) {
        this.tblJadwalAjarDosen = tblJadwalAjarDosen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUploadNilai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxmatkul;
    private javax.swing.JComboBox<String> jComboBoxsemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtextnama;
    private javax.swing.JTextField jtextnilaimhs;
    private javax.swing.JTextField jtextnim;
    private javax.swing.JTable tblJadwalAjarDosen;
    // End of variables declaration//GEN-END:variables

    
}
